CREATE TABLE PRIORITIES (
   ID     SERIAL      PRIMARY KEY,
   PRIORITY VARCHAR(50) NOT NULL UNIQUE CHECK (STATUS ~ '\S')
);

CREATE TABLE TICKET_STATUS (
   ID     SERIAL      PRIMARY KEY,
   STATUS VARCHAR(50) NOT NULL UNIQUE CHECK (STATUS ~ '\S')
);

CREATE TABLE CATEGORIES (
   ID     SERIAL      PRIMARY KEY,
   CATEGORY VARCHAR(50) NOT NULL UNIQUE CHECK (STATUS ~ '\S')
);

CREATE TABLE TICKETS (
   ID            UUID         PRIMARY KEY,
   TECHNICIAN_ID UUID,
   CUSTOMER_ID   UUID         NOT NULL
   TITLE         VARCHAR(50)    NOT NULL,
   DESCRIPTION   VARCHAR(250)   NOT NULL CHECK (DESCRIPTION ~ '\S'),
   PRIORITY_ID   INT            REFERENCES PRIORITIES(ID),
   STATUS_ID     INT            REFERENCES TICKET_STATUS(ID),
   CATEGORY_ID   INT            REFERENCES CATEGORIES(ID),
   CREATED_AT    TIMESTAMP      NOT NULL,
   UPDATED_AT    TIMESTAMP      NOT NULL CHECK (UPDATED_AT >= CREATED_AT)
);

INSERT INTO PRIORITIES (PRIORITY) VALUES ('LOW');
INSERT INTO PRIORITIES (PRIORITY) VALUES ('MEDIUM');
INSERT INTO PRIORITIES (PRIORITY) VALUES ('HIGH');
INSERT INTO PRIORITIES (PRIORITY) VALUES ('CRITICAL');

INSERT INTO TICKET_STATUS (STATUS) VALUES ('OPEN');
INSERT INTO TICKET_STATUS (STATUS) VALUES ('IN_PROGRESS');
INSERT INTO TICKET_STATUS (STATUS) VALUES ('WAITING');
INSERT INTO TICKET_STATUS (STATUS) VALUES ('RESOLVED');
INSERT INTO TICKET_STATUS (STATUS) VALUES ('CLOSED');

INSERT INTO CATEGORIES (CATEGORY) VALUES ('HARDWARE');
INSERT INTO CATEGORIES (CATEGORY) VALUES ('SOFTWARE');
INSERT INTO CATEGORIES (CATEGORY) VALUES ('NETWORK');